version: "3.9"  # optional since v1.27.0

services: 

  mynodejsapp:
    build:
      dockerfile: node-backend/Dockerfile
      context: ./
    networks:
      - warroom
    ports:
      - 3000:8080
    restart: always
    environment:
      DATABASE_USER: admin
      DATABASE_PASSWORD: 1111
      DATABASE_HOST: mymongodb
networks:
  warroom:
    driver: bridge